spring:
  profiles:
    active: prod # Set default profile ./gradlew bootRun --args='--spring.profiles.active=dev'
                 # or --spring.profiles.active=prod

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://dpg-cmuok6acn0vc73akdjfg-a.oregon-postgres.render.com:5432/new_postgresql_for_javalin
    username: new_postgresql_for_javalin_user
    password: GvGwspqIZhAYD3HDJjbP9QP51RSh5yf9

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

logging:
  level:
    org:
      springframework:
        web: DEBUG
        boot:
          autoconfigure:
            web: DEBUG

sentry:
  dsn: 'https://32cbc15a350637bfb2bd67a6d666a60b@o4507171956391936.ingest.de.sentry.io/4507171977101392'
  traces-sample-rate: 1.0  # Захват 100% транзакций для мониторинга производительности